apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ${CHATOPS_NAME}
  namespace: ${INFRA_NAMESPACE}
  labels:
    app: ${CHATOPS_NAME}
    app.kubernetes.io/name: ${CHATOPS_NAME}
    app.kubernetes.io/component: chatops
    app.kubernetes.io/part-of: data-engineering-platform
    app.kubernetes.io/managed-by: openshift
spec:
  lookupPolicy:
    local: true
