# Optional: Shared PostgreSQL instance for demos or monitoring
# Teams typically deploy their own databases in their namespaces
# Deploy with: kubectl apply -f postgres.yaml -n ${INFRA_NAMESPACE}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: ${INFRA_NAMESPACE:-${INFRA_NAMESPACE}}
type: Opaque
stringData:
  postgres-password: "postgres-admin"  # Change this!
  database-name: "mydatabase"
  database-user: "dbuser"
  database-password: "CHANGE_THIS_PASSWORD"  # Change this!

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: ${INFRA_NAMESPACE:-${INFRA_NAMESPACE}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2  # Adjust to your cluster's storage class

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ${INFRA_NAMESPACE:-${INFRA_NAMESPACE}}
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgresql
          image: registry.redhat.io/rhel8/postgresql-13:latest
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: database-name
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 1000m
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRESQL_USER
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRESQL_USER
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ${INFRA_NAMESPACE:-${INFRA_NAMESPACE}}
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
  selector:
    app: postgres
